apiVersion: v1
kind: Service
metadata:
  name: fuseki-operator-controller-manager-metrics
  namespace: fuseki-system
  labels:
    app.kubernetes.io/name: fuseki-operator
    control-plane: controller-manager
spec:
  selector:
    app.kubernetes.io/name: fuseki-operator
    control-plane: controller-manager
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics