package controller

import (
	"fmt"
	"sort"
	"strings"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/util/intstr"

	fusekiv1alpha1 "github.com/larsw/k8s-fuseki-operator/api/v1alpha1"
)

const (
	securityConfigVolumeName = "security-config"
	securityTLSVolumeName    = "security-tls"
	securityTLSMountPath     = "/fuseki-extra/security/tls"
	securityTLSCertFile      = securityTLSMountPath + "/tls.crt"
	securityTLSKeyFile       = securityTLSMountPath + "/tls.key"
	securityTLSCAFile        = securityTLSMountPath + "/ca.crt"
	datasetConfigMountPath   = "/fuseki-extra/dataset-config"
	authorizationConfigDir   = "/fuseki-extra/authorization"
	authorizationIndexFile   = authorizationConfigDir + "/policies.index"
	rangerConfigFile         = authorizationConfigDir + "/ranger.properties"
)

type datasetBootstrapTarget struct {
	Kind               string
	Name               string
	Image              string
	ImagePullPolicy    corev1.PullPolicy
	WriteURL           string
	SecurityProfileRef *corev1.LocalObjectReference
}

func securityProfileTLSEnabled(profile *fusekiv1alpha1.SecurityProfile) bool {
	return profile != nil && profile.Spec.TLSSecretRef != nil && profile.Spec.TLSSecretRef.Name != ""
}

func fusekiListenerScheme(profile *fusekiv1alpha1.SecurityProfile) string {
	if securityProfileTLSEnabled(profile) {
		return "https"
	}
	return "http"
}

func fusekiProbeScheme(profile *fusekiv1alpha1.SecurityProfile) corev1.URIScheme {
	if securityProfileTLSEnabled(profile) {
		return corev1.URISchemeHTTPS
	}
	return corev1.URISchemeHTTP
}

func fusekiProbeHandler(profile *fusekiv1alpha1.SecurityProfile, port int32) corev1.ProbeHandler {
	if securityProfileTLSEnabled(profile) {
		return corev1.ProbeHandler{Exec: &corev1.ExecAction{Command: []string{
			"/bin/sh",
			"-ec",
			fmt.Sprintf("curl --silent --show-error --fail --insecure https://127.0.0.1:%d/$/ping >/dev/null", port),
		}}}
	}

	return corev1.ProbeHandler{HTTPGet: &corev1.HTTPGetAction{
		Scheme: fusekiProbeScheme(profile),
		Path:   "/$/ping",
		Port:   intstr.FromInt32(port),
	}}
}

func fusekiStartupProbe(profile *fusekiv1alpha1.SecurityProfile, port int32) *corev1.Probe {
	return &corev1.Probe{
		ProbeHandler:        fusekiProbeHandler(profile, port),
		FailureThreshold:    30,
		PeriodSeconds:       5,
		InitialDelaySeconds: 5,
	}
}

func fusekiReadinessProbe(profile *fusekiv1alpha1.SecurityProfile, port int32) *corev1.Probe {
	return &corev1.Probe{
		ProbeHandler:        fusekiProbeHandler(profile, port),
		PeriodSeconds:       5,
		InitialDelaySeconds: 10,
	}
}

func fusekiLivenessProbe(profile *fusekiv1alpha1.SecurityProfile, port int32) *corev1.Probe {
	return &corev1.Probe{
		ProbeHandler:        fusekiProbeHandler(profile, port),
		PeriodSeconds:       10,
		InitialDelaySeconds: 15,
	}
}

func fusekiServicePortName(profile *fusekiv1alpha1.SecurityProfile) string {
	if securityProfileTLSEnabled(profile) {
		return "https"
	}
	return "http"
}

func secureServiceURL(rawURL string, profile *fusekiv1alpha1.SecurityProfile) string {
	if !securityProfileTLSEnabled(profile) {
		return rawURL
	}

	return strings.Replace(rawURL, "http://", "https://", 1)
}

func renderFusekiConfigData(resourceName string, datasetRefs []corev1.LocalObjectReference, httpPort int32, writeServiceName string) map[string]string {
	datasetNames := joinLocalObjectReferences(datasetRefs)
	fusekiTTL := strings.Join([]string{
		"# Generated by fuseki-operator",
		"@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
		"@prefix fuseki: <http://jena.apache.org/fuseki#> .",
		"",
		"[] rdf:type fuseki:Server .",
	}, "\n") + "\n"

	properties := []string{
		"resource.name=" + resourceName,
		fmt.Sprintf("http.port=%d", httpPort),
		"write.service=" + writeServiceName,
		"datasets=" + datasetNames,
	}

	runScript := strings.Join([]string{
		"set -eu",
		"launcher_classpath=\"/opt/fuseki/fuseki-server.jar:/opt/fuseki/fuseki-operator-launcher.jar:/opt/fuseki/fuseki-operator-deps/*\"",
		"if [ -n \"${SECURITY_PROFILE_TLS_CERT_FILE:-}\" ] || [ -n \"${SECURITY_PROFILE_TLS_KEY_FILE:-}\" ]; then",
		"  if [ ! -f \"${SECURITY_PROFILE_TLS_CERT_FILE:-}\" ] || [ ! -f \"${SECURITY_PROFILE_TLS_KEY_FILE:-}\" ]; then",
		"    echo \"TLS configuration requested but certificate files are missing\" >&2",
		"    exit 1",
		"  fi",
		"  https_dir=\"${FUSEKI_BASE}/https\"",
		"  mkdir -p \"${https_dir}\"",
		"  chmod 700 \"${https_dir}\"",
		"  https_password_file=\"${https_dir}/https.passwd\"",
		"  if [ ! -f \"${https_password_file}\" ]; then",
		"    openssl rand -hex 18 > \"${https_password_file}\"",
		"    chmod 600 \"${https_password_file}\"",
		"  fi",
		"  https_password=$(cat \"${https_password_file}\")",
		"  keystore_file=\"${https_dir}/keystore.p12\"",
		"  https_config=\"${https_dir}/https.json\"",
		"  rm -f \"${FUSEKI_BASE}/shiro.ini\"",
		"  openssl pkcs12 -export -name jetty -in \"${SECURITY_PROFILE_TLS_CERT_FILE}\" -inkey \"${SECURITY_PROFILE_TLS_KEY_FILE}\" -out \"${keystore_file}\" -passout \"pass:${https_password}\" >/dev/null 2>&1",
		"  chmod 600 \"${keystore_file}\"",
		"  printf '{ \"keystore\": \"%s\", \"passwd\": \"%s\" }\n' \"${keystore_file}\" \"${https_password}\" > \"${https_config}\"",
		"  PATH=/opt/fuseki:${PATH:-}",
		"  exec \"${JAVA_HOME}/bin/java\" -cp \"${launcher_classpath}\" FusekiHttpsLauncher --config=/fuseki-extra/operator-config/fuseki-server.ttl --https=\"${https_config}\" --httpsPort ${FUSEKI_PORT:-" + fmt.Sprintf("%d", httpPort) + "}",
		"fi",
		"exec \"${JAVA_HOME}/bin/java\" -cp \"${launcher_classpath}\" FusekiHttpsLauncher --config=/fuseki-extra/operator-config/fuseki-server.ttl --port ${FUSEKI_PORT:-" + fmt.Sprintf("%d", httpPort) + "}",
	}, "\n") + "\n"

	return map[string]string{
		"fuseki-server.ttl": fusekiTTL,
		"run-fuseki.sh":     runScript,
		"server.properties": strings.Join(properties, "\n") + "\n",
	}
}

func renderRDFDeltaConfigData(server *fusekiv1alpha1.RDFDeltaServer) map[string]string {
	properties := []string{
		"service.name=" + server.ServiceName(),
		fmt.Sprintf("service.port=%d", server.DesiredServicePort()),
		fmt.Sprintf("retention.days=%d", server.DesiredRetentionDays()),
		"storage.path=" + fusekiv1alpha1.DefaultRDFDeltaDataMountPath,
	}

	runScript := strings.Join([]string{
		"set -eu",
		"exec ${RDF_DELTA_COMMAND:-rdf-delta-server} --port ${RDF_DELTA_PORT} --storage ${RDF_DELTA_STORAGE_PATH}",
	}, "\n") + "\n"

	return map[string]string{
		"rdf-delta.properties": strings.Join(properties, "\n") + "\n",
		"run-rdf-delta.sh":     runScript,
	}
}

func fusekiDatasetConfigVolumeForRefs(refs []corev1.LocalObjectReference) corev1.Volume {
	if len(refs) == 0 {
		return corev1.Volume{Name: datasetConfigVolumeName, VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}}}
	}

	sources := make([]corev1.VolumeProjection, 0, len(refs))
	for _, ref := range refs {
		if ref.Name == "" {
			continue
		}
		optional := true
		sources = append(sources, corev1.VolumeProjection{
			ConfigMap: &corev1.ConfigMapProjection{
				LocalObjectReference: corev1.LocalObjectReference{Name: ref.Name + "-dataset-config"},
				Optional:             &optional,
				Items: []corev1.KeyToPath{
					{Key: "dataset.properties", Path: ref.Name + "/dataset.properties"},
					{Key: "preload.txt", Path: ref.Name + "/preload.txt"},
					{Key: "spatial.properties", Path: ref.Name + "/spatial.properties"},
					{Key: "security-policies.json", Path: ref.Name + "/security-policies.json"},
					{Key: "security-policies.missing", Path: ref.Name + "/security-policies.missing"},
				},
			},
		})
	}

	return corev1.Volume{
		Name:         datasetConfigVolumeName,
		VolumeSource: corev1.VolumeSource{Projected: &corev1.ProjectedVolumeSource{Sources: sources}},
	}
}

func renderFusekiServiceList(datasetRefs []corev1.LocalObjectReference) string {
	if len(datasetRefs) == 0 {
		return ""
	}

	services := make([]string, 0, len(datasetRefs))
	for _, ref := range datasetRefs {
		services = append(services, fmt.Sprintf("<%s>", ref.Name))
	}
	sort.Strings(services)
	return strings.Join(services, " ")
}

func fusekiAdminEnvVars(adminSecretRef *corev1.LocalObjectReference) []corev1.EnvVar {
	if adminSecretRef == nil || adminSecretRef.Name == "" {
		return nil
	}

	optional := true
	return []corev1.EnvVar{{
		Name: "ADMIN_PASSWORD",
		ValueFrom: &corev1.EnvVarSource{SecretKeyRef: &corev1.SecretKeySelector{
			LocalObjectReference: *adminSecretRef,
			Key:                  "password",
			Optional:             &optional,
		}},
	}}
}

func renderSecurityProfileConfigData(profile *fusekiv1alpha1.SecurityProfile) map[string]string {
	if profile == nil {
		return map[string]string{"security.properties": ""}
	}

	properties := make([]string, 0, 8)
	properties = append(properties, "authorization.mode="+string(profile.DesiredAuthorizationMode()))
	if profile.Spec.AdminCredentialsSecretRef != nil && profile.Spec.AdminCredentialsSecretRef.Name != "" {
		properties = append(properties, "admin.secretRef="+profile.Spec.AdminCredentialsSecretRef.Name)
	}
	if profile.Spec.TLSSecretRef != nil && profile.Spec.TLSSecretRef.Name != "" {
		properties = append(properties,
			"tls.secretRef="+profile.Spec.TLSSecretRef.Name,
			"tls.mountPath="+securityTLSMountPath,
			"tls.certFile="+securityTLSCertFile,
			"tls.keyFile="+securityTLSKeyFile,
			"tls.caFile="+securityTLSCAFile,
		)
	}
	if profile.DesiredOIDCIssuerURL() != "" {
		properties = append(properties, "oidc.issuerURL="+profile.DesiredOIDCIssuerURL())
	}
	if profile.DesiredOIDCClientID() != "" {
		properties = append(properties, "oidc.clientID="+profile.DesiredOIDCClientID())
	}
	properties = append(properties,
		"authorization.dir="+authorizationConfigDir,
		"authorization.indexFile="+authorizationIndexFile,
		"authorization.failClosed=true",
	)
	if profile.RangerAuthorizationEnabled() {
		properties = append(properties,
			"ranger.adminURL="+profile.Spec.Authorization.Ranger.AdminURL,
			"ranger.serviceName="+profile.Spec.Authorization.Ranger.ServiceName,
			"ranger.configFile="+rangerConfigFile,
			"ranger.pollInterval="+desiredRangerPollInterval(profile),
		)
		if profile.Spec.Authorization.Ranger.AuthSecretRef != nil && profile.Spec.Authorization.Ranger.AuthSecretRef.Name != "" {
			properties = append(properties, "ranger.authSecretRef="+profile.Spec.Authorization.Ranger.AuthSecretRef.Name)
		}
	}
	sort.Strings(properties)

	return map[string]string{
		"security.properties": strings.Join(properties, "\n") + "\n",
	}
}

func fusekiSecurityEnvVars(profile *fusekiv1alpha1.SecurityProfile) []corev1.EnvVar {
	if profile == nil {
		return nil
	}

	env := []corev1.EnvVar{
		{Name: "SECURITY_PROFILE_NAME", Value: profile.Name},
		{Name: "SECURITY_PROFILE_CONFIG_DIR", Value: "/fuseki-extra/security"},
		{Name: "SECURITY_PROFILE_CONFIG", Value: "/fuseki-extra/security/security.properties"},
		{Name: "SECURITY_PROFILE_AUTHORIZATION_MODE", Value: string(profile.DesiredAuthorizationMode())},
		{Name: "FUSEKI_DATASET_CONFIG_DIR", Value: datasetConfigMountPath},
		{Name: "FUSEKI_AUTHORIZATION_DIR", Value: authorizationConfigDir},
		{Name: "FUSEKI_AUTHORIZATION_INDEX", Value: authorizationIndexFile},
		{Name: "FUSEKI_AUTHORIZATION_FAIL_CLOSED", Value: "true"},
	}
	if profile.DesiredOIDCIssuerURL() != "" {
		env = append(env, corev1.EnvVar{Name: "SECURITY_PROFILE_OIDC_ISSUER", Value: profile.DesiredOIDCIssuerURL()})
	}
	if profile.DesiredOIDCClientID() != "" {
		env = append(env, corev1.EnvVar{Name: "SECURITY_PROFILE_OIDC_CLIENT_ID", Value: profile.DesiredOIDCClientID()})
	}
	if profile.RangerAuthorizationEnabled() {
		env = append(env,
			corev1.EnvVar{Name: "SECURITY_PROFILE_RANGER_ADMIN_URL", Value: profile.Spec.Authorization.Ranger.AdminURL},
			corev1.EnvVar{Name: "SECURITY_PROFILE_RANGER_SERVICE_NAME", Value: profile.Spec.Authorization.Ranger.ServiceName},
			corev1.EnvVar{Name: "SECURITY_PROFILE_RANGER_CONFIG", Value: rangerConfigFile},
			corev1.EnvVar{Name: "SECURITY_PROFILE_RANGER_POLL_INTERVAL", Value: desiredRangerPollInterval(profile)},
		)
		if profile.Spec.Authorization.Ranger.AuthSecretRef != nil && profile.Spec.Authorization.Ranger.AuthSecretRef.Name != "" {
			optional := true
			env = append(env,
				corev1.EnvVar{Name: "SECURITY_PROFILE_RANGER_AUTH_SECRET", Value: profile.Spec.Authorization.Ranger.AuthSecretRef.Name},
				corev1.EnvVar{
					Name: "SECURITY_PROFILE_RANGER_USERNAME",
					ValueFrom: &corev1.EnvVarSource{SecretKeyRef: &corev1.SecretKeySelector{
						LocalObjectReference: *profile.Spec.Authorization.Ranger.AuthSecretRef,
						Key:                  "username",
						Optional:             &optional,
					}},
				},
				corev1.EnvVar{
					Name: "SECURITY_PROFILE_RANGER_PASSWORD",
					ValueFrom: &corev1.EnvVarSource{SecretKeyRef: &corev1.SecretKeySelector{
						LocalObjectReference: *profile.Spec.Authorization.Ranger.AuthSecretRef,
						Key:                  "password",
						Optional:             &optional,
					}},
				},
			)
		}
	}
	if profile.Spec.TLSSecretRef != nil && profile.Spec.TLSSecretRef.Name != "" {
		env = append(env,
			corev1.EnvVar{Name: "FUSEKI_SERVER_SCHEME", Value: "https"},
			corev1.EnvVar{Name: "SECURITY_PROFILE_TLS_SECRET", Value: profile.Spec.TLSSecretRef.Name},
			corev1.EnvVar{Name: "SECURITY_PROFILE_TLS_DIR", Value: securityTLSMountPath},
			corev1.EnvVar{Name: "SECURITY_PROFILE_TLS_CERT_FILE", Value: securityTLSCertFile},
			corev1.EnvVar{Name: "SECURITY_PROFILE_TLS_KEY_FILE", Value: securityTLSKeyFile},
			corev1.EnvVar{Name: "SECURITY_PROFILE_TLS_CA_FILE", Value: securityTLSCAFile},
		)
	}

	return env
}

func desiredRangerPollInterval(profile *fusekiv1alpha1.SecurityProfile) string {
	if profile == nil || !profile.RangerAuthorizationEnabled() {
		return "30s"
	}
	if profile.Spec.Authorization.Ranger.PollInterval.Duration > 0 {
		return profile.Spec.Authorization.Ranger.PollInterval.Duration.String()
	}
	return "30s"
}

func fusekiSecurityConfigVolume(profile *fusekiv1alpha1.SecurityProfile) *corev1.Volume {
	if profile == nil {
		return nil
	}

	return &corev1.Volume{
		Name: securityConfigVolumeName,
		VolumeSource: corev1.VolumeSource{ConfigMap: &corev1.ConfigMapVolumeSource{
			LocalObjectReference: corev1.LocalObjectReference{Name: profile.ConfigMapName()},
		}},
	}
}

func fusekiSecurityConfigVolumeMount(profile *fusekiv1alpha1.SecurityProfile) *corev1.VolumeMount {
	if profile == nil {
		return nil
	}

	return &corev1.VolumeMount{Name: securityConfigVolumeName, MountPath: "/fuseki-extra/security", ReadOnly: true}
}

func fusekiSecurityTLSVolume(profile *fusekiv1alpha1.SecurityProfile) *corev1.Volume {
	if profile == nil || profile.Spec.TLSSecretRef == nil || profile.Spec.TLSSecretRef.Name == "" {
		return nil
	}

	optional := true
	return &corev1.Volume{
		Name: securityTLSVolumeName,
		VolumeSource: corev1.VolumeSource{Secret: &corev1.SecretVolumeSource{
			SecretName: profile.Spec.TLSSecretRef.Name,
			Optional:   &optional,
		}},
	}
}

func fusekiSecurityTLSVolumeMount(profile *fusekiv1alpha1.SecurityProfile) *corev1.VolumeMount {
	if profile == nil || profile.Spec.TLSSecretRef == nil || profile.Spec.TLSSecretRef.Name == "" {
		return nil
	}

	return &corev1.VolumeMount{Name: securityTLSVolumeName, MountPath: securityTLSMountPath, ReadOnly: true}
}
