package controller

import (
	"fmt"
	"sort"
	"strings"

	corev1 "k8s.io/api/core/v1"

	fusekiv1alpha1 "fuseki-operator/api/v1alpha1"
)

type datasetBootstrapTarget struct {
	Kind               string
	Name               string
	Image              string
	ImagePullPolicy    corev1.PullPolicy
	WriteURL           string
	SecurityProfileRef *corev1.LocalObjectReference
}

func renderFusekiConfigData(resourceName string, datasetRefs []corev1.LocalObjectReference, httpPort int32, writeServiceName string) map[string]string {
	datasetNames := joinLocalObjectReferences(datasetRefs)
	fusekiTTL := strings.Join([]string{
		"# Generated by fuseki-operator",
		"@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
		"@prefix fuseki: <http://jena.apache.org/fuseki#> .",
		"",
		"[] rdf:type fuseki:Server .",
	}, "\n") + "\n"

	properties := []string{
		"resource.name=" + resourceName,
		fmt.Sprintf("http.port=%d", httpPort),
		"write.service=" + writeServiceName,
		"datasets=" + datasetNames,
	}

	runScript := strings.Join([]string{
		"set -eu",
		"exec /opt/fuseki/fuseki-server --config=/fuseki-extra/operator-config/fuseki-server.ttl --port ${FUSEKI_PORT:-" + fmt.Sprintf("%d", httpPort) + "}",
	}, "\n") + "\n"

	return map[string]string{
		"fuseki-server.ttl": fusekiTTL,
		"run-fuseki.sh":     runScript,
		"server.properties": strings.Join(properties, "\n") + "\n",
	}
}

func renderRDFDeltaConfigData(server *fusekiv1alpha1.RDFDeltaServer) map[string]string {
	properties := []string{
		"service.name=" + server.ServiceName(),
		fmt.Sprintf("service.port=%d", server.DesiredServicePort()),
		fmt.Sprintf("retention.days=%d", server.DesiredRetentionDays()),
		"storage.path=" + fusekiv1alpha1.DefaultRDFDeltaDataMountPath,
	}

	runScript := strings.Join([]string{
		"set -eu",
		"exec ${RDF_DELTA_COMMAND:-rdf-delta-server} --port ${RDF_DELTA_PORT} --storage ${RDF_DELTA_STORAGE_PATH}",
	}, "\n") + "\n"

	return map[string]string{
		"rdf-delta.properties": strings.Join(properties, "\n") + "\n",
		"run-rdf-delta.sh":     runScript,
	}
}

func fusekiDatasetConfigVolumeForRefs(refs []corev1.LocalObjectReference) corev1.Volume {
	if len(refs) == 0 {
		return corev1.Volume{Name: datasetConfigVolumeName, VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}}}
	}

	sources := make([]corev1.VolumeProjection, 0, len(refs))
	for _, ref := range refs {
		optional := true
		sources = append(sources, corev1.VolumeProjection{
			ConfigMap: &corev1.ConfigMapProjection{
				LocalObjectReference: corev1.LocalObjectReference{Name: ref.Name + "-dataset-config"},
				Optional:             &optional,
			},
		})
	}

	return corev1.Volume{
		Name:         datasetConfigVolumeName,
		VolumeSource: corev1.VolumeSource{Projected: &corev1.ProjectedVolumeSource{Sources: sources}},
	}
}

func renderFusekiServiceList(datasetRefs []corev1.LocalObjectReference) string {
	if len(datasetRefs) == 0 {
		return ""
	}

	services := make([]string, 0, len(datasetRefs))
	for _, ref := range datasetRefs {
		services = append(services, fmt.Sprintf("<%s>", ref.Name))
	}
	sort.Strings(services)
	return strings.Join(services, " ")
}

func fusekiAdminEnvVars(adminSecretRef *corev1.LocalObjectReference) []corev1.EnvVar {
	if adminSecretRef == nil || adminSecretRef.Name == "" {
		return nil
	}

	optional := true
	return []corev1.EnvVar{{
		Name: "ADMIN_PASSWORD",
		ValueFrom: &corev1.EnvVarSource{SecretKeyRef: &corev1.SecretKeySelector{
			LocalObjectReference: *adminSecretRef,
			Key:                  "password",
			Optional:             &optional,
		}},
	}}
}
