apiVersion: v1
kind: Service
metadata:
  name: fuseki-operator-webhook-service
  namespace: fuseki-system
spec:
  selector:
    app.kubernetes.io/name: fuseki-operator
    control-plane: controller-manager
  ports:
    - port: 443
      protocol: TCP
      targetPort: webhook-server
      name: https