apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fuseki-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - fuseki.apache.org
    resources:
      - '*'
    verbs:
      - '*'
