apiVersion: fuseki.apache.org/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
  namespace: default
spec:
  name: primary
  type: TDB2
  securityPolicies:
    - name: example-securitypolicy
  spatial:
    enabled: true
    assembler: spatial:EntityMap
    spatialIndexPath: spatial
