apiVersion: fuseki.apache.org/v1alpha1
kind: SecurityProfile
metadata:
  name: example-securityprofile
  namespace: default
spec:
  adminCredentialsSecretRef:
    name: example-admin-secret
  tlsSecretRef:
    name: example-tls-secret
  oidc:
    issuerURL: https://issuer.example.com
    clientID: fuseki-ui
  authorization:
    mode: Local