apiVersion: fuseki.apache.org/v1alpha1
kind: FusekiCluster
metadata:
  name: example
  namespace: default
spec:
  replicas: 3
  image: ghcr.io/larsw/k8s-fuseki-operator/fuseki:6.0.0
  httpPort: 3030
  rdfDeltaServerRef:
    name: example-delta
  datasetRefs:
    - name: example-dataset
  securityProfileRef:
    name: example-securityprofile
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  storage:
    accessMode: ReadWriteOnce
    size: 2Gi
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/fuseki
                operator: In
                values:
                  - "true"
  observability:
    metrics:
      service:
        annotations:
          prometheus.io/scrape: "true"
      serviceMonitor:
        labels:
          release: prometheus
    logging:
      podAnnotations:
        logs.example.com/enabled: "true"

