apiVersion: fuseki.apache.org/v1alpha1
kind: ImportRequest
metadata:
  labels:
    app.kubernetes.io/name: k8s-fuseki-operator
    app.kubernetes.io/managed-by: kustomize
  name: example-importrequest
  namespace: default
spec:
  target:
    datasetRef:
      name: example-dataset
  source:
    type: S3
    uri: s3://example-bucket/bootstrap/example-dataset.nq.gz
    format: application/n-quads
