resources:
  - fuseki_v1alpha1_backuppolicy.yaml
  - fuseki_v1alpha1_restorerequest.yaml
  - fuseki_v1alpha1_fusekicluster.yaml
  - fuseki_v1alpha1_fusekiserver.yaml
  - fuseki_v1alpha1_rdfdeltaserver.yaml
  - fuseki_v1alpha1_dataset.yaml
  - fuseki_v1alpha1_endpoint.yaml
  - fuseki_v1alpha1_fusekiui.yaml
  - fuseki_v1alpha1_securityprofile.yaml
  - fuseki_v1alpha1_securityprofile_ranger.yaml
  - fuseki_v1alpha1_securitypolicy.yaml
  - fuseki_v1alpha1_shaclpolicy.yaml
  - fuseki_v1alpha1_importrequest.yaml
  - fuseki_v1alpha1_exportrequest.yaml
  - fuseki_v1alpha1_ingestpipeline.yaml
  - fuseki_v1alpha1_changesubscription.yaml
