resources:
  - fuseki_v1alpha1_backuppolicy.yaml
  - fuseki_v1alpha1_restorerequest.yaml
  - fuseki_v1alpha1_fusekicluster.yaml
  - fuseki_v1alpha1_fusekiserver.yaml
  - fuseki_v1alpha1_rdfdeltaserver.yaml
  - fuseki_v1alpha1_dataset.yaml
  - fuseki_v1alpha1_endpoint.yaml
  - fuseki_v1alpha1_fusekiui.yaml
  - fuseki_v1alpha1_securityprofile.yaml
