#!/bin/sh

set -eu

port=1066

while [ "$#" -gt 0 ]; do
	case "$1" in
		--port)
			port="$2"
			shift 2
			;;
		--storage)
			shift 2
			;;
		*)
			shift
			;;
	esac
done

while true; do
	nc -lk -p "$port" >/dev/null 2>&1
done