{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fuseki-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "fuseki-operator.labels" . | indent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
